### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-Community#1]
Test test

**Comment by SM-BJS** [comment]
Passing this to @SM-Stotey

**Comment by SM-Stotey** [comment]
Test

**Comment by SM-Stotey** [comment]
So unfortunately only the contributors can assign the issue labels, I can't change it.

**Comment by SM-BJS** [comment]
Could you create a new test issue and see if the creator of the issue can change it?

**Comment by SM-Stotey** [comment]
#2 

I think it's due to me not having 'Write' access to the Team/Repo/Project.
