### ISSUE TITLE
Thermal optics

### ISSUE THREAD

**Issue by Baxter0004** [StowMarines/StowMarines-Community#101]
Thermal optics that can be attached to Rifles should be Blacklisted for balancing reasons.

these include:
-AN/PAS-13G(V)1
-Nightstalker
-TWS
-TWS MG

with these scopes, soldiers can make out Targets at multiple kilometres. 
as soon as the thermal optics get upgraded we might be able to loosen the rule on thermal optics but for now they have to be blacklisted.

**Comment by SM-BJS** [comment]
Cool, I’ll look into it once I’ve fully recovered.

**Comment by SM-BJS** [comment]
The AN/PAS-13G(V)1 was already blacklisted and I double checked, it's still blacklisted. All of the other scopes have now been blacklisted in Framework Version 1.5.5
