### ISSUE TITLE
ASP-1 Kir Blacklist

### ISSUE THREAD

**Issue by CurvedKiwi** [StowMarines/StowMarines-Community#102]
ASP-1 Kir is a variant of the AS VAL, but chambered in 12.7mm which is what the M107 Barrett is chambered in. It can disable a T-72 in 6 shots, and also penetrate through a BTR's armour eliminating crew and absolutely destroy a BRDM. If the Barrett is blacklisted I feel like this needs to also be as it serves the same use as what the M107 does.

**Comment by SM-BJS** [comment]
Agreed

**Comment by SM-BJS** [comment]
This item has now been blacklisted in Framework Version 1.5.5
