### ISSUE TITLE
Mod suggestion - Ratworks Insurgent Zeus Module

### ISSUE THREAD

**Issue by PANZERSHREK** [StowMarines/StowMarines-Community#103]
Tiny .4Mb mod that allows Zeus to bury IEDs leaving only a small cable showing. Works with all IED mods and ACE interaction to detect disable. Great for  immersion etc
https://steamcommunity.com/sharedfiles/filedetails/?id=2458094846&searchtext=ratworks

**Comment by SM-BJS** [comment]
Very interesting find! I'll forward this onto leadership and the contract brokers. The only issue I can find with this is that we sometimes miss IEDs as they are already, nonetheless I'll see what the guys think about it and get back to you.

**Comment by SM-BJS** [comment]
After checking the mod out and testing it as well as discussion with leadership, I think we are going to have to give this one a miss. I came across a couple of bugs when using the mod where multiple explosions would be instantaneously triggered when an AI were given waypoints, causing them to explode too early and causing lag spikes. 

The bury IED feature worked fine, but after discussing with leadership, a lot of people fail to see IEDs as they are already and there are only a couple of situations where Zeuses could take advantage of the feature without people getting triggered by the fact that Zeus blew them up with something they can barely see.
