### ISSUE TITLE
HQ POSTERS

### ISSUE THREAD

**Issue by PANZERSHREK** [StowMarines/StowMarines-Community#104]
Hi would it be an idea to have a poster put up in the HQ arsenal room showing the minimum loadout items - ctab, helmet cam, medical in back pack etc. May make life easier for apps and serve as a reminder. Also maybe a second one by the door/building exit with brief rules on magazine capacities, marksman scopes, AT weapons etc - medics not carrying NLAWS etc. One of the challenges we get in personnel is "where does it say that" - would make "policing" easier.

**Comment by SM-BJS** [comment]
Brilliant idea! l've added it to my to do list 👍🏼

**Comment by SM-BJS** [comment]
Implemented in Training Map Update 9.2.2
