### ISSUE TITLE
Custom mods directory for new users

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#107]
Could the SMI be programmed upon installation to create a custom subfolder in the steam arma 3 directory for the mods, so the workshop mods don't interfere? The reason I request this is due to the applicants having to do this manually as can be seen on mod support channel, which fixes all the issues experienced, you yourself i believe have fixed biggsy's directory when it showed overwritten mods by workshop. Then the SMI would need to be given the subfolder path, which I hope can be done without user intervention? My guess would be something along the lines of mods directory = install location/SMImods subfolder. E.G:
![Screenshot_59](https://user-images.githubusercontent.com/86921632/190616296-2b82dc12-acf2-4cd8-a3e6-863d9fc8e3bb.png)

**Comment by SM-BJS** [comment]
SMI shouldn't ever call from workshop, that's Arma3Sync, so if you use the repo of A3S and SMI, it will use A3S downloads (which use workshop). 

If you only use SMI, it shouldn't be a problem. Do you have a link to the issue in mod-support so I can have a look at it?

**Comment by SM-BJS** [comment]
Now that I've reviewed this, I don't think it's a bad idea, I'll add it to my to do list. This will be moved over to Discord.
