### ISSUE TITLE
4th Zeus slot

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#109]
Petitioning for a 4th zeus slot. There have been issues with ops and training with regards to zeus numbers. Most notably, we used to have always 3 zeuses constantly during ops, now we have at best 2 at a time with 2 additional units being kratos and athena, increasing the workload with less zeuses. At least a temporary 4th slot would be appreciated as there have been times where on a saturday only grinning was zeusing or only jasper.

**Comment by SM-BJS** [comment]
Are you referring to adding another module or another person? Another thing we have to consider is for every Zeus that is running, FPS is reduced fairly drastically.

**Comment by wearhint** [comment]
I mean another person

**Comment by SonicBacon** [comment]
3 Zeus's should be enough to run any op but having a 4th wouldn't hurt as there will be always something for them to do. either adding to role play or taking control of enemy units. As things currently stand we're lucky to have 2 on for ops. The issue would be to find players that would rather setup and tribute to missions as opposed to being in a squad completing mission objectives .

**Comment by SM-BJS** [comment]
After a few conversations, we've decided not to go with a fourth Zeus because of the FPS deduction and the fact that we should already more than enough. Instead we will focus on our current Zeuses and try to improve attendance/missions through them.
