### ISSUE TITLE
ACE Medical Vitals bug

### ISSUE THREAD

**Issue by SM-Stotey** [StowMarines/StowMarines-Community#11]
After giving IV and Epinephrine vitals sometimes continue to drop rapidly.

**Comment by SM-BJS** [comment]
@SM-Stotey You discussed the other night about this not being a bug, do we have a final verification of this?

**Comment by SM-Stotey** [comment]
@SM-BJS I have looked into the ACE Medical repo and there are no known issues relating to this being a bug so for now we should continue to assess if restoring the volume of blood fully fixes the blood pressure loss even after all open wounds are patched/stitched.

**Comment by SM-BJS** [comment]
@SM-Stotey Sounds good. If after a week or two you think it is a bug, I'd recommend reporting it because a lot of people/communities simply don't report it (take the ACRE bug for example).
