### ISSUE TITLE
New map consideration

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#110]
Not a request, just here's a cool map: https://steamcommunity.com/sharedfiles/filedetails/?id=2857846877

**Comment by SM-BJS** [comment]
I've taken a look at it, it's a pretty cool map, my main concern is that it's a bit of a Fallujah turn out, as in there's an amazing cool city and not much else around it so the amount we could use it could be limited, but there's definitely at least 4 missions you could make out of it so I've added it to the contract brokers list of potential future maps.
