### ISSUE TITLE
Jerry can addition to the base

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#111]
I would like to request a few jerry cans to be added either in the inventory of the fuel truck on the airfield or as an option in the crate/logistics shed. The reason is that in case of a fueltank breach, the fuel leaks out very fast, in case of enemy fire, it is sometimes not possible to jump out and immediately repair, causing a vehicle to become useless even if repaired 100%. There is no siphon hose to get fuel from other vehicles, however ace has jerry cans that can fit instead of a wheel in the ace inventory or just attached to the side of the vehicle, giving a few miles to the fuel inventory in case of total fuel loss. Just enough to trek back to base for a re-fuel.

**Comment by SM-BJS** [comment]
Carried over to Discord.
