### ISSUE TITLE
Remove vanilla NODs / vanilla helmet mounts

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#13]
Vanilla NOD's are inherently unrealistic due to a unrealistically large FOV or specs - especially with the panoramic version and the Gen. 4 version by ACE. Our modpack currently contains two good realistic NOD's - the PVS 14 and PVS 15, that are fully ACE night vision compatible.

Included in this change should also be the removal of vanilla helmets, as they use helmet mounts that are not compatible with NOD's from the real world (but are compatible in Arma, resulting in hovering mounts). For this, our modpack features a magnitude of different high quality helmets that use the real helmet mount.

And honestly, vanilla NOD's look pretty dumb compared to the realistic mod counterparts, but that's of course just an opinion.

**Comment by SM-BJS** [comment]
Hi Markus, thanks for bringing this up.

I agree with your points and I have brought it up to the leadership team. Once I get some feedback from them I will get back to you.

**Comment by SM-BJS** [comment]
The strong majority of the leadership team also agree with your points and so within the coming week or two I will look at implementing this into both the framework and the training map.

I will post updates here where appropriate.

**Comment by SM-BJS** [comment]
After some testing, the following NVGs will be removed:

- NV Goggles (All)
- ENVG-II (All)

And the following Vanilla Helmets that weren't blacklisted previously will be removed as they cause the hovering NVG affect:

- Avenger Helmet (All)
- Advanced Modular Helmet (All)
- Stealth Combat Helmet (All)
- Modular Helmet

**Comment by SM-BJS** [comment]
The changes have been implemented.
