### ISSUE TITLE
Advanced Vault System - Alternative to Enhanced Movement

### ISSUE THREAD

**Issue by SMHawaiian** [StowMarines/StowMarines-Community#16]
Sadly author of **Enhanced Movement stopped supporting** his mod, which will result in **no more updates**. I'm linking this mod since not only it is being currently **regularly updated**, but also features **amazing animations** further enhancing immersion. I've played with this mod loaded for a couple of hours, and till this point did not have any issues with it.

_https://steamcommunity.com/sharedfiles/filedetails/?id=2193322331_

_Sincerely,
[SM]Hawaiian_

**Comment by SM-BJS** [comment]
Hi Hawaiian, thanks for the mod suggestion. 

This mod does look good and would be a solid alternative to Enhanced Movement. I will give it and it's dependency a test (WMO) when I can and I'll get back to you.

**Comment by SM-BJS** [comment]
I gave this a test today. It is a little bit buggy, for example: when you vault over a custom object (which most of our maps contain) it sometimes makes you float over or through the object. 

The animations are cool and it has great potential, however I am torn. 

If people could give it a test themselves for the next week or so (not on the server but in singleplayer) and let me know on their opinions that'd be great.

**Comment by SM-BJS** [comment]
I will test to see if ACEX Sitting works with this mod as Enhanced Movement and ACEX are incompatible (which causing the sitting issues)

**Comment by SM-BJS** [comment]
Closing this for now, we can re-visit this in a few months time to see if it less buggy than Enhanced Movement.
