### ISSUE TITLE
OP Vanilla Launchers

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#17]
After some looking around, i found that all Vanilla launchers are either OP or can be replaced by a more realistic one in our mods:
The Maaws MK4 Mod1 Has a built in range finder + Night vision
The Maaws MK4 Mod0 have none but would still be better than the M3 Maaws in every aspect
RPG-32 has built in NVG
The Metis and the Titan can be replaced by the javelin
Titan AA OP and we should use either the igla or the Stinger

Conclusion: M3 Maaws and MK153 Mod0 SMAW are the LAT that should be used | Javelin as HAT | Stinger and Igla as AA.

**Comment by SM-BJS** [comment]
I agree with all of the above and I'll implement it within the next week or two.

**Comment by SM-BJS** [comment]
After looking into the current blacklist, all of the Titan launchers are already blacklisted but the following launchers have now been blacklisted and it has been implemented on both the Framework and the Training Map:

- MAAWS Mk4 Mod 0 (All)
- MAAWS Mk4 Mod 1 (All)
- RPG-32 (All)
- Metis-M (All)
