### ISSUE TITLE
New Test

### ISSUE THREAD

**Issue by SM-Stotey** [StowMarines/StowMarines-Community#2]
Label Test

**Comment by SM-Stotey** [comment]
Unable to assign this a label too @SM-BJS 

Perhaps a permissions error?

**Comment by SM-BJS** [comment]
Hmmm let me have a look around. At least the issue creator should have access to label themselves as I did on the ACRE one GitHub.

**Comment by SM-BJS** [comment]
Try now

**Comment by SM-Stotey** [comment]
Brilliant, fixed.
