### ISSUE TITLE
Add Troop Corpsman slot to Artemis

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#22]
Currently, I need to request medical permissions from the Contract Brokers before start of any mission - with it sometimes not working or me simply forgetting it before departing.

(Artemis requires a dedicated medic as they usually operate in a detached fashion, often needing to stay unrecognized by the enemy, making medical support both from air and land unsuitable.)

**Comment by SM-BJS** [comment]
The design of the medical team is that the CMO delegates the CMT to the teams on the night dependant on the operation at hand and the tasks that you will execute. 

The current CMO (Triumph) will be contacting a member or two to get them in the CMT slot after Wednesday's CMT Ribbon session.
