### ISSUE TITLE
Potential new maps

### ISSUE THREAD

**Issue by SMJasper** [StowMarines/StowMarines-Community#23]
https://steamcommunity.com/sharedfiles/filedetails/?id=648172507
https://steamcommunity.com/sharedfiles/filedetails/?id=837413362

You told me to put them on the github. Have fun. Very nice.

**Comment by SM-BJS** [comment]
Please discuss with your fellow Contract Brokers to discuss a day and time that the server will be free next week to test and I will add it then for you to test on the server.

**Comment by SM-BJS** [comment]
#25
