### ISSUE TITLE
Updated map list for testing

### ISSUE THREAD

**Issue by SMJasper** [StowMarines/StowMarines-Community#25]
Here are the maps we would like to test this Sunday.

1. https://steamcommunity.com/workshop/filedetails/?id=680808574
2. https://steamcommunity.com/workshop/filedetails/?id=1537973181
3. https://steamcommunity.com/sharedfiles/filedetails/?id=1291778160
4 . https://steamcommunity.com/sharedfiles/filedetails/?id=718649903
5. https://steamcommunity.com/sharedfiles/filedetails/?id=1282716647
6. https://steamcommunity.com/sharedfiles/filedetails/?id=648172507

They are in order of testing, so we don't have to test them all on one day.

**Comment by SM-BJS** [comment]
1. Requires a mod that we do not have so I will delay that mod testing till a later date.
2. This map has been tested in the past (a long time ago), so it can be tested at a later date.
3. Looks good, I will add this for testing this Sunday.
4. The StowMarines used to operate on the Lingor/Dingor maps and shouldn't cause any problems but I will schedule it for testing this Sunday.
5. Again, looks good, I will leave this to be tested another time (maybe over the Christmas break).
6. This has been tested in the past and I will schedule it for another time.

The following two maps will be added to the server for testing this Sunday: Hellanmaa & Lingor/Dingor Island

**Comment by SM-BJS** [comment]
To test the two maps, you will have to make a local copy of the mods (as it will not be added to the A3S repo until testing is complete).

**Comment by SM-BJS** [comment]
Diyala will not be added due to the extra required mod adding an extra half a gig to the mod.

**Comment by SM-BJS** [comment]
Anizay
VIDDA | Legacy Version
G. O. S. Al Rayak

Are to be tested today by @SMJasper

**Comment by SM-BJS** [comment]
Testing has been completed.

VIDDA will not be added due to a lack of enterable buildings and areas to operate in for the StowMarines.

Anizay and G. O. S Al Rayak will be added.
