### ISSUE TITLE
Radio Problem

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#26]
Hello, i had a couple of issues lately regarding radios.
I could not hear certain people on the same channel but they could hear me.
sometimes i could hear a couple of transmissions from other channels but it is not consistent.

**Comment by SM-BJS** [comment]
One or two other people had similar issues regarding ACRE yesterday. ACRE has not updated recently so we are going to suspect that this was an anomaly. I will leave this open to see if any issues arise this evening.

**Comment by SM-BJS** [comment]
There was no outstanding issues this Saturday, but I will leave this open for another weekend to be certain.

**Comment by SM-BJS** [comment]
No issues this weekend either so I'm putting this down to an anomaly.
