### ISSUE TITLE
Live Targets despawning after random time

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-Community#28]
The live targets in all arenas are spawning in correctly for all clients, but they seem to despawn themselves after a random amount of time.

**Comment by SM-BJS** [comment]
This issue _should_ now be fixed. I will leave it up to @Mariusstad and/or @SonicBacon to test this during the week or on Friday.

**Comment by SM-BJS** [comment]
I tested this today with Marc and there was no bug in sight. I will leave this to be stress-tested this Friday when a whole team use it.

**Comment by SM-BJS** [comment]
Tested this again with Halli (now the script has been placed on all Arenas) and no bugs were raised. I will now leave this to mass testing on Friday from Marius and/or Sonic.

**Comment by SonicBacon** [comment]
Going to test it out as well in about an hour, will let you know if I find any issues.

**Comment by SonicBacon** [comment]
All seems to work great. Only thing I did find was on the second cqc dome, there’s a guy who spawns on the balcony and spots you straight away through the windows in the dome doors. Tbh I quite like and catches you off guard. That was the closest thing I could find to an issue so great work 👍

**Comment by SM-BJS** [comment]
Awesome, thanks Sonic, I'll leave the guy on the balcony there for now, if he gets on people's nerves I can move him in the future. I'll leave this open until this Saturday.

**Comment by SM-BJS** [comment]
After mass testing today, there were no bugs found with the CQC Arena. If you find anything else in the future, please open a new issue.
