### ISSUE TITLE
Vcom AI

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#31]
In light of the recent removal of ASR AI I talked to David and we both would like to recommend Vcom AI as a replacement.

Pros:
* Flanking maneuvers of the AI
* AI finds effective cover, making sniper rabbit hunting a lot harder
* AI searches lost contacts
* Good utilization of vehicles and heavy weapons (even artillery)
* Customizable chance of AI ragdoll when hit
* Highly customizable parameters

Cons:
* Vcom AI creates custom waypoints that are visible to Zeus. Zeus needs to be aware of the modified AI behaviour and tune the mission accordingly to utilize it
* Vcom AI has an impact on mission performance. BUT a lot less units are required for challenging missions, keeping it much more interesting even with smaller forces
* It would change the general "feel" of the missions quite drastically, but IMO in a more immersive and exciting way.

Pro/Con:
* Vcom AI will not engage enemy forces when overwhelmed, they will fall back

**Comment by SM-BJS** [comment]
ASR AI was removed as it was controlling AI over Zeus and was slightly causing an effect on FPS. It was removed for testing during January and will be put back on if it doesn't fix the problem. 

We have used Vcom in the past and we switched to ASR AI as it caused us quite a few problems and ASR AI fixed most of those.

So either way at the end of the testing month for ASR AI, I doubt we would use Vcom.

I will leave this open for the rest of the weekend incase anyone else has an opinion on it.

**Comment by markusa380** [comment]
@SM-BJS Out of curiosity, could you tell me what kind of issues you have experienced with Vcom?

**Comment by SM-BJS** [comment]
I haven't got a list at hand since this was under the responsibilities of an old member (who has left). But I believe it was along the lines of causing lag/desync but also being a pain in the rear for Zeus (more so than ASR AI).

**Comment by SM-BJS** [comment]
At the request of the mission makers, ASR AI will be re-added.
