### ISSUE TITLE
AI unconsciousness

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#32]
It still seems like AI cannot go unconscious, making for frustrating CQC encounters with anything below 7.62mm.

**Comment by SM-BJS** [comment]
I'll take a look into the medical settings for AI. Is this in the CQC arena(s) or everywhere? And do you know what factions (or all)?

**Comment by markusa380** [comment]
@SM-BJS A while back I performed some testing and never achieved unconsciousness on AI no matter the equipment.
I have never seen AI go unconscious in any of our mission since then (this was before the USMC => PMC transition).
It should happen quite regulary, as it happens pretty often the other way around so to speak.

**Comment by SM-BJS** [comment]
There is an Ace Medical setting that disallows AI to go unconscious, we did this because people weren't enjoying shooting an enemy seeing him go unconscious then wake up and kill them. I can re-enable it for the following week and see how it goes.

**Comment by markusa380** [comment]
I'd suggest explicitly briefing teams that some extra bullets to the head of incapacitated units are good measure. Not sure what Warsaw has to say about that though...
________________________________

**Comment by SM-BJS** [comment]
I have enabled AI Unconsciousness and have lowered the AI Critical Damage Threshold to 0.80. We'll use this weekend as a test to see if things improve.

**Comment by SM-BJS** [comment]
Tested this out with Marc today, the AI are now going unconscious, the targets are still taking a fair few bullets to go down even with the unconscious enabled and the damage required lowered to 0.80 so I have lowered it to 0.50 for the weekend.

**Comment by CurtisTheBossman** [comment]
Having the AI wake up again was a surprise tonight but was overall I thought it was cool, its just a bit bullshit when they wake up after getting sprayed in the chest, 180 spin on the floor and down you. It will definitely change the way we play as we had people waking up all around us in training tonight. One thing I would like to check on is do the AI need to follow the same rules as a human player waking up (needing heart rate and enough blood).

**Comment by markusa380** [comment]
@CurtisTheBossman See the comment on the other thread.

**Comment by SM-BJS** [comment]
As the majority is mixed on this subject, I will keep it enabled for this week and the following week. 

After this I will host a vote on our Discord. Where the majority lies is where the decision will be pushed towards (unless any outstanding issues arise).

**Comment by markusa380** [comment]
Some other options we have:
- Enable ACE hit reactions / other hit reactions mod that allows enemy units to fall down when hit, but stand up immediately. Would solve CQC issues without need of unconsciousness.
- Tune options to make chance of AI waking up lower, while chance of going unconscious stays the same or is set marginally lower.

**Comment by markusa380** [comment]
![107410_20210116151628_1](https://user-images.githubusercontent.com/5033990/104814207-e84b4c00-580d-11eb-8cb5-5555a6cda993.png)

This looks like the heart rate behaviour is not consistent between players and AI...

**Comment by SM-BJS** [comment]
The outcome of the vote has decided that AI Unconsciousness will be disabled.
