### ISSUE TITLE
Blacklist headwear with "integrated" night vision

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#34]
Seems like we have a lot of headwear that has night vision "integrated" into it, which is of course kind of ridiculous and aimed at casual players. I suggest we blacklist such. It should be possible by filtering out any headwear with night vision in the Cfg - as real NVGs are in the NVG category, not the headwear one.

**Comment by SM-BJS** [comment]
I'll look into the blacklist and filter this out as I agree with you.

**Comment by SM-BJS** [comment]
All TRYK Face & Head Gear with Integrated NV blacklisted.
