### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#36]
HK121(Tan): the Hex variant is blacklisted. It is a 9.3mm Machine gun with a ridiculous 1500rpm fire rate (try it out with burst fire mode)

LWMMG(all variants): .338 machine gun with no recoil. Has more range than a sniper rifle.

RCO(PIP) Optic from ace: it makes your frames drop and there is the Leupold Mark 4 HAMR optics which are the same just different name and don't make your frames drop

**Comment by SM-BJS** [comment]
All weapons have been blacklisted. 

There is an issue that is not allowing me to blacklist the RCO (PIP) so I am going to create a separate issue for that as it will take longer to sort out.

**Updated Blacklist:**
https://docs.google.com/document/d/1TgypH428JvqFKKRj9r2G-VTsebHLdO3YFfPktMLou38/edit?usp=sharing
