### ISSUE TITLE
Bullets needed to kill downed AI 5.56

### ISSUE THREAD

**Issue by mattBops** [StowMarines/StowMarines-Community#40]
This is in fairness the worst case that I came across but whilst using 5.56 mk262 ammo in the CQC domes it was taking a high amount of rounds to down AI and a large amount of rounds to kill the AI whilst they were down. AI also seemed to wake back up more frequently when downed by 5.56 as well compared to 7.62. 

Video of this happening: https://streamable.com/qvu2fy

**Comment by SM-BJS** [comment]
Unfortunately with the change of the AI Unconscious state, they can take infinite damage without dying, it is only if they take a fatal shot to the head or a bare torso. 

I will link this to issue #32 to see if any variables can be changed to help with this problem but it will be a heavy weighing factor into whether we turn AI unconsciousness back off.

**Comment by SonicBacon** [comment]
I’m so happy this issue was brought up, thought I was going mad with the amount of rounds I was putting into the AI to kill them, using 7.62 AP rounds seem to help but then your stuck with a weapon that’s not really suited for cqc.

I think with the AI unconsciousness we just need to start putting a round into their head if we go past them and make sure the guys don’t get too trigger happy in doing so.

**Comment by SMJasper** [comment]
I agree with Matt and Sonic here. I have been noticing as a Zeus that AI turn to civilian and just lay there for a good while until they either die or come back to live. It seems they are too unkillable this way and it takes too many bullets from the guys on the ground when they shoot targets who are supposed to be KIA. I suggest putting the settings back to how they were previously.

**Comment by SM-BJS** [comment]
Thanks for bringing these up, I'll attach them to issue #32

**Comment by markusa380** [comment]
Just to comment on this.

AI now has behaviour very similar to how players get downed.

This has certain effects that everyone needs to be aware of.

Shooting an enemy will now make them drop considerably faster than before, as the bullets tend to "shock" them into unconsciousness, much like it happens with players.

But, as others have noted, they don't die right away, and are pretty hard to kill in general.

This isn't bad. **DO NOT GET FRUSTRATED.**
This means team leaders need to educate their teams into handling downed enemies differently.

First, you don't necessarily need to completely kill them. Others have commented that you should dump the mag or shoot in their heads. This is wrong. Shoot them two to three more times, center of mass or if possible the head. **They might not "die" but they sure as hell won't wake up anymore and bleed out.**

Second, bring cableties and educate yourself and others to take prisoners whenever possible. I'm sure our contractors will reward that adequately.

The unconscious system **MASSIVELY** improves CQC play if you adjust to it. Suddenly, even pistols and low caliber guns take care of knocking the enemy over in just a couple of shots, giving your team the edge to control the situation before sending them off to doot town or taking them prisoner.

Again, do not get frustrated. Adapt and overcome, so we can all have a more consistent and dynamic experience in our missions.

**Comment by markusa380** [comment]
@SMJasper @SonicBacon @mattBops @SM-BJS

**Comment by SM-BJS** [comment]
#32
