### ISSUE TITLE
T-14 on vehicle targeting range have Hard-kill APS enabled 

### ISSUE THREAD

**Issue by Mariusstad** [StowMarines/StowMarines-Community#41]
The T-14 have a Hard-kill Active protective system (APS) which simply forces any anti-tank rockets or rounds to explode within a 10 meter radius of the tank before getting a chance to make a dent in the armor. The T-14 we have on the vehicle targeting range have Hard-Kill APS enabled, not only does the APS make the T-14 even more invincible but it also disrupts rockets meant for other targets. I fired an RPG at a T-72 which was 10-15 meters away from the T-14, and the round exploded before it reached the T-72 because of the T-14's APS. 

[https://ibb.co/9ygz4vd](url)

**Comment by SM-BJS** [comment]
Thanks for letting me know, that link doesn't work by the way. @Halliwedge was this what was also causing Helios some problems?

**Comment by Halliwedge** [comment]
Affirm, Attached is the image Drago captured when hitting targets on the AT range with rockets/missiles. 
![unknown](https://user-images.githubusercontent.com/68269584/104787949-ec815600-5788-11eb-9a17-35d1177f8255.png)

**Comment by Mariusstad** [comment]
You can't turn off the system either, it is automatic or whatever, also just select the link and paste it if you want to see the image

**Comment by SM-BJS** [comment]
I found this on the web: 
_"The RHS devs are very clear that the T14 is still in testing, and the APS isn’t working properly (there’s a reason that “HARD KILL ACTIVATED” message comes up)."_

I will delete the T-14 from the range until the devs finish the tank.
