### ISSUE TITLE
White Phosphor

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#42]
A tiny mod (~0.5MB) that might improve the reception of night missions:

https://steamcommunity.com/sharedfiles/filedetails/?id=1792394837

**Pros:**
* It looks better
* Less eye strain
* No config required - replaces green phosphor in all devices

**Cons:**
* 0.5MB modpack addition

**Comment by SM-BJS** [comment]
This mod is incompatible with the A3 Improved Thermal mod that we use.

**Comment by markusa380** [comment]
That's unfortunate. I wonder why, as A3TI doesn't affect night vision.

**Comment by markusa380** [comment]
If this is a topic @SM-BJS would be interested in, another option probably would be forking & building a custom version of ACE3. It's rather easy as ACE3 provides scripts for building and a nice description of the prerequisites.

**Comment by SM-BJS** [comment]
Forking and building a custom version of Ace is something I can look into in the future, but at the moment it is pretty unnecessary and time consuming.

**Comment by markusa380** [comment]
@SM-BJS I have already done it before and could provide you the built version if it turns out to be possible.
