### ISSUE TITLE
PVS-27 Interact

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#43]
A microscopically small mod that allows attaching/detaching the PVS-27 night vision attachment for both the M8541A optic or the TA31RCO from RHS.

https://steamcommunity.com/sharedfiles/filedetails/?id=933524188

**Pros:**
* No need to bring two identical scopes with and without attachment

**Cons:**
* 0.05MB increased mod pack size

**Comment by SM-BJS** [comment]
Is there no easy alternative to adding another mod?

**Comment by markusa380** [comment]
I don't think so, this functionality isn't included in RHS.
It should be, because the models already exist, which doesn't make a lot of sense because the NV attachment alone doesn't have a reticle and cannot be used for aiming, but is still included in RHS for some reason.

**Comment by SM-BJS** [comment]
And there's not another NV scope that can be used instead?

**Comment by markusa380** [comment]
The scopes can be used just fine. This is just an improvement that doesn't require carrying one scope with and one scope without attachment and swapping them out when needed. I assumed that it would be a valid functional addition given it's small size.

**Comment by SM-BJS** [comment]
I brought this up with unit leadership and it was deemed as an unnecessary addition at this point in time.
