### ISSUE TITLE
Suggestion for a new mod

### ISSUE THREAD

**Issue by SMJasper** [StowMarines/StowMarines-Community#46]
3CB Factions provides the contract brokers with more options of creativity in missions. I have been noticing that we have been getting a bit limited after using the same infantry/vehicles for a long time. This mod adds better versions of current existing factions like the Middle Eastern Militia and it adds new factions that have not been used before.

https://steamcommunity.com/sharedfiles/filedetails/?id=1673456286

**Comment by SM-BJS** [comment]
I have looked into this mod and definitely has a lot of good things for Zeus to utilise. I would like to point out though that most of these assets come from CUP and the CUP mods combined are a smaller file size than this mod. That being said, this mods would be easier to keep up to date as it is in a single mod. 

I would like all the contract brokers to test it out this week. If you you guys feel it is definitely worth it for the file size, we will add it.

**Comment by Ranzarth** [comment]
Adds some very nice content, especially for civilians which I like, would be a good addition.

**Comment by SM-BJS** [comment]
This was successfully utilised this week and had a good addition to the unit's mission and didn't cause any issues from what we are aware of, therefore this mod will remain in the modpack.
