### ISSUE TITLE
Zeus slot

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#49]
Sometimes logging in in zeus actual or any zeus slot doesn't give me zeus. Temporary fix is that i reslot into another zeus slot and hope it works.

**Comment by SM-BJS** [comment]
I have stress tested it and haven't had this issue on my end. @Ranzarth @SMJasper can you guys give this a test as well see if happens to you.

**Comment by Ranzarth** [comment]
Haven't experienced this issue on training personally

**Comment by SM-BJS** [comment]
With the change in mods recently, Zeus seems to load a lot quicker, let me know if it has also solved this issue @SM-Marc

**Comment by SM-Marc** [comment]
The problem is still there.I think it's somehow related to internet connection as it has happened to me and marius only and we both have bad internet.

**Comment by SM-BJS** [comment]
That seems like a valid reason since it hasn't happened to anyone else. I'll leave this open for the rest of this weekend encase anyone else has similar issues, if not, I'll close it.

As a side note, do you try and load Zeus as soon as you spawn in? Or is it after some time?

**Comment by SM-Marc** [comment]
It doesn't really matter when. When you press Y instead of going into zeus you ping zeus. But yeah no big issue slotting in another zeus slot works 90% of the times.

**Comment by SM-BJS** [comment]
I'm now closing this issue. If the issue becomes more common and worse, please open up a new issue.
