### ISSUE TITLE
CQC arena options

### ISSUE THREAD

**Issue by davidpiksi** [StowMarines/StowMarines-Community#50]
Basically an option that would let you spawn more armored units from a different faction. This could be added to the drop down menu, just like the new heal option was added a while back. This would let us get more acquainted with cqc when we're up against more difficult enemies

**Comment by SM-BJS** [comment]
Sounds good, I will look into it.

**Comment by SM-BJS** [comment]
I've finished scripting the system for this and the tests in multiplayer have been successful. Do you have a short list of the main factions you'd like implemented?

**Comment by davidpiksi** [comment]
Oh pog. The RHS AFRF probably have a decent amount of armor, as do the PMCs. Not sure how exactly the spawning system works but maybe just to keep the units consistent you put in the Russians only

**Comment by SM-BJS** [comment]
Sounds good. The system works with specific factions, so if there's like a particular bundle of factions that you would like to see spawned, let me know and I'll implement it. You can see the factions we have available to us in the 3DEN Editor.

**Comment by davidpiksi** [comment]
The OPFOR Russian VDV and INDEP PMCs have a lot of armor. Would be good to practice against those targets

**Comment by SM-BJS** [comment]
Implemented VDV and PMC into the scripts. This will be publicly released in Version Update 1.3
