### ISSUE TITLE
Mod Suggestion: Starstreak HVM Missile System

### ISSUE THREAD

**Issue by BOMBERMANTRUE** [StowMarines/StowMarines-Community#53]
I have been fascinated by the British made Starstreak HVM system for a while now and was looking into it's potential uses with SM and personally I think it would be a very effective platform for infantry. It is capable (and very effective) of engaging rotary-wing and fixed-wing aircraft and has also been proven effective against soft-skin, APC and IFV class vehicles. I understand that we already have separate weapon platforms for engaging vehicles of these types, I just thought that it would be more effective to have a weapon system capable of engaging all of these vehicle types with reliable accuracy and an extremely fast projectile (Mach 4+). I have found a Steam workshop mod that is highly rated and contains multiple variants of the Starstreak.
https://steamcommunity.com/sharedfiles/filedetails/?id=859380377&searchtext=Starstreak

**Comment by SM-BJS** [comment]
I will look into it, however:
- Artemis is too powerful as it is
- It would remove some of the Anti Air tasks that Helios currently do (and still isn't enough)
- We already have weapons that do the same task
- It is rare that would need AA weaponry more efficient than that of what we already have access to

I will pass this onto Unit Leadership.

**Comment by SM-BJS** [comment]
It was brought up with unit leadership and the decision was to not add this mod primarily due to the above reasons.
