### ISSUE TITLE
Blacklist suggestion

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#55]
There is 6 bags called "Camp" that have 0 load capacity but their job is to assemble them and when assembled they turn into a respawn point.

Also there is 3 Bags called "Remote designator Bag". Don't really know what it's purpose. Same as the other bag no load capacity. When assembled it turns into a bot laser designator on a tripod.

**Comment by BOMBERMANTRUE** [comment]
The remote designator is controlled with a UAV terminal (I think) and is literally just a laser designator on a turret mount, so it can be used to precisely guide munitions such as JDAMs.

**Comment by SM-BJS** [comment]
I will blacklist the resawn bags, and will look into the designator bag.

**Comment by SM-BJS** [comment]
The camps have been blacklisted in Training Map Update V1.4.1. I will leave this open until I have blacklisted them in the framework as well.

**Comment by SM-BJS** [comment]
Released in framework version 1.3.1
