### ISSUE TITLE
Potential Base Addition: Heavy Vehicle Training Area

### ISSUE THREAD

**Issue by BOMBERMANTRUE** [StowMarines/StowMarines-Community#56]
I was thinking that once Kratos is put into effect: So that the crew can practise with their vehicles, why not create an area (if it hasn't already been done) for driving and firing vehicles like MBTs and IFVs? Just thought it would allow the crew to get a better feel for the vehicles available to them before entering a live fire scenario.

**Comment by SM-BJS** [comment]
I'll look into it.

**Comment by SM-BJS** [comment]
Spoke with Marius as to what was needed. Implemented in V1.4.1
