### ISSUE TITLE
CH/ACE View distance issue

### ISSUE THREAD

**Issue by Halliwedge** [StowMarines/StowMarines-Community#58]
CH view distance is changing the fog wall, but the "Object" slider doesn't affect anything in game.

**Comment by SM-BJS** [comment]
After removing MRB, Dynamic View and turning off all Ace3 settings that override distance, the mod now seems to be working properly, I will leave this open until you can confirm it is fixed @Halliwedge

**Comment by Halliwedge** [comment]
Works like a charm.

**Comment by SM-BJS** [comment]
Awesome! This ticket is now closed.
