### ISSUE TITLE
Arsenal bug

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#60]
Sometimes with the same arsenal and the same time, some people see the blacklisted items and others cannot. And that's for all the arsenal.

**Comment by SM-BJS** [comment]
I don't believe there's much I can do about this, it's simply the fact that the file that executes this is called slower on some machines than it is on other machines, I'll still look into it though.

**Comment by SM-BJS** [comment]
Have you still been experiencing this issue?

**Comment by SM-Marc** [comment]
I will double check this weekend for the last time and i'll let you know.

**Comment by SM-BJS** [comment]
Any update on this?

**Comment by SM-Marc** [comment]
Not at the moment. most probably client side.
