### ISSUE TITLE
SPS BlackHornet PRS

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#63]
https://steamcommunity.com/sharedfiles/filedetails/?id=2457052493

* Uses vanilla drone terminal
* Can be carried in the inventory
* Doesn't bug out when flying to a waypoint
* Limited turning angle of the turret, making it a little more interesting to use
* Very smol
* Mod creator is already household in our modpack

**Comment by SM-BJS** [comment]
Looks like a good mod and the creators are from my old unit so I'm sure it will be of good quality, my only concern would be the fact that we are looking at removing the use of the Darter due to it being to OP and ruining the mission, how would this drone be any better?

**Comment by markusa380** [comment]
I'd recommend trying it out yourself - it has it's own set of limitations.

**Comment by SM-BJS** [comment]
Brought this up with unit leadership and although it does look like a really cool mod, it would harm the already fine-line balance between Artemis and the rest of the unit, so we will not be adding it.
