### ISSUE TITLE
Map suggestion

### ISSUE THREAD

**Issue by SM-Marc** [StowMarines/StowMarines-Community#64]
Kingdom of Regero
https://steamcommunity.com/sharedfiles/filedetails/?id=2278254320

I have not tried it before, hopefully it doesnt have bad FPS and radios works without issue. But by the looks of it it's nice.

**Comment by SM-BJS** [comment]
Just taken a look at it and although it is a very cool map, it's mainly open terrain with hardly any enterable buildings, but I'll leave this up to the mission makers @Ranzarth @SMJasper _(love that they literally put proving grounds in the actual map lol)_

**Comment by SMJasper** [comment]
I wasn't a big fan of the map when I looked at it a while back; I can check the map at a later time and see if anything changed.

**Comment by Ranzarth** [comment]
Map seems good, suffers from some quality issues in some parts, and the amount of enterable buildings is tolerable, wouldn't be a bad map to add.

**Comment by SM-BJS** [comment]
It will be added to the mission maker's list of potential future maps.
