### ISSUE TITLE
CTAB unit visibility issues

### ISSUE THREAD

**Issue by Ranzarth** [StowMarines/StowMarines-Community#65]
The CTAB seems to show enemy units as Bluefor on the CTAB, this was an issue with enemy independent units on the mission Dorphin, seems to only show vehicles.

**Comment by DeanWalsh** [comment]
I am not 100% sure but I thought I saw some infantry units at the start of the mission on the CTAB too, platoon markers?

**Comment by SM-Stotey** [comment]
I am not 100% sure but I thought I saw some infantry units at the start of the mission on the CTAB too, platoon markers?

Sorry for spam, I used the wrong account to comment initially.

**Comment by SM-BJS** [comment]
The enemies that appear, were they initially spawned in as indi/blufor then their faction/side relations changed? Or were they spawned from OPFOR and not changed?

**Comment by SM-BJS** [comment]
I am looking at transferring our cTab version over to the Devastator variant, hopefully this will fix the issue.
