### ISSUE TITLE
Suggestion: Add FATA

### ISSUE THREAD

**Issue by markusa380** [StowMarines/StowMarines-Community#67]
https://steamcommunity.com/sharedfiles/filedetails/?id=909332315

A nice map using CUP assets which could be useful for future missions.
I have fond memories playing on it with my old group in the past.

**Comment by SM-BJS** [comment]
Passed over to the mission makers for review.

**Comment by SMJasper** [comment]
Just checked out the map. It looks good; military bases look clean and well-designed and the towns are interesting. My only problem with it that everything is centered around a single valley. This will probably mean that after two missions, the map will have been fully explored.

**Comment by SM-BJS** [comment]
This mod will be added to the contract list of potential maps for future use.
