### ISSUE TITLE
more efficient mod download

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#88]
Hi, writing this here to not attract attention on discord, just throwing an idea: can we make it possible to have the new mods/updates come in compressed so we don't have to download the full size? A script that packs for send-off and unpacks to client. It would be alot easier if a script like this is available open source, neat to include it in SMI to make it even better

**Comment by SM-BJS** [comment]
Hi Wearhint, 

Funnily enough, I did look into this not so long ago. It's definitely worth looking back into now that we have a new download system in place, I'll add it to my to-do list, thanks for the suggestions!

**Comment by SM-BJS** [comment]
Successfully got all fresh downloads working with a zipped variant, halving download time, and reducing lines of code by around 50, thanks a lot for the suggestion!
