### ISSUE TITLE
new suggestion

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#89]
Hi again,

I was looking at bots for discord and found nadekobot which gives timed messages, so for example op time in x minutes, which will help with people with various time zones. Screenshot from bot commands: https://i.gyazo.com/ee1fd56dd1dac3e165e4238cdaf5e8bf.png

**Comment by SM-BJS** [comment]
This looks really cool and I could definitely see the benefit in this, especially for applicants and the like. Is there a feature to set up a reminder for each week at the same time/day?

**Comment by wearhint** [comment]
i think so, one of the commands is by hours, so by setting it at like every 168 and 150 hours or something it should just auto remind for saturdays and fridays forever, only have to modify it for daylight savings and shit

**Comment by SM-BJS** [comment]
Drago looked into it and couldn't find a feature that would let us repeat it every week.

Furthermore he found that YAGPDB.xyz (which we already have) has a feature to send out messages but again it can't repeat every week for example, it'd have to be done on the day.

**Comment by SM-BJS** [comment]
StowMarines bot developed by Marc has added this functionality.
