### ISSUE TITLE
Huron Crates (spawning option)

### ISSUE THREAD

**Issue by DragoSMPog** [StowMarines/StowMarines-Community#90]
Anton asked if we could add the Huron repair/ammo/fuel crates to the Helicopter spawners in the FOB, and I think it would be nice to add it, and it would make it easier, because right now, if zeus is doing RP, we may be waiting back at base for a while, meanwhile Kratos needs repairs or rearming.

**Comment by SM-BJS** [comment]
I'll add it to my list to look into with the new training map and framework update.

**Comment by SM-BJS** [comment]
Tested and implemented into Framework 1.5.3

**Comment by SM-BJS** [comment]
Tested on & implemented into the current training map
