### ISSUE TITLE
auto-download feature

### ISSUE THREAD

**Issue by wearhint** [StowMarines/StowMarines-Community#95]
Not an issue, just a suggestion. Could SMI have an auto-download feature so if a person has left their pc open and are at work or smt they can download the mods? I remember you saying that mod updates get sent after weekend, so ops aren't affected so this might only be a niche instance where it is useful.

**Comment by SM-BJS** [comment]
If you are on about a fully autonomous background process-based system, I'd probably avoid having that feature as if a mod is corrupt, I won't have any time to stop the update post the initial send out, therefore the end-user would install the corrupt version and would have to wait to manually get the fresh one.

I do see how this would benefit users who are absent from their PC, and that with a complete redesign/re-code of the server side modules and client update fetching it would be possible, but I think with privacy and safety in mind (as well avoiding a re-write), it would be best if we avoided implementing this kind of a system, thanks for the suggestion though.

_This post will remain open for a day or two for any further responses._
