### ISSUE TITLE
FO LR Comms to FC

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-Community#96]
Add the long-range communications section from the FO ribbon to the FC ribbon and catch anyone up who has the FC ribbon but not an FO ribbon.

**Comment by SM-BJS** [comment]
Unless I'm confused, the LR section was always in the FC ribbon (according to the changelogs). After looking at the Training Tracker and considering what ribbons others have, only Bomber would have to be caught up on this section if it was not already taught to him @Halliwedge

**Comment by Halliwedge** [comment]
Pretty sure I went over it with him, but due to me not being able to attend training I'm not sure when I can go through it full with him. I might ask Training team to assist. @SM-BJS

**Comment by SM-BJS** [comment]
I'll close this issue and forward it onto Training Team.
