### ISSUE TITLE
Respawn menu issue

### ISSUE THREAD

**Issue by Baxter0004** [StowMarines/StowMarines-Community#98]
on the training map it appears that when the AI shoots you dead (not down, dead) the Respawn menu bugs out. 

the courser is gone which means that you cannot interact with the menu anymore.
![image](https://user-images.githubusercontent.com/95487963/181783537-2a879158-9a21-4501-a3d3-1e71c65cf8b5.png)
it still shows where the courser would be with the Red lines but the courser itself isn't there which means that you cannot interact with the whole menu.

pressing Space or Enter also doesn't allow you to interact with the "Respawn" button.
the Escape key also looses all function, the only option from that point is to close the game with the task manager

 this appears to only happen when an AI ,after downing you, continues to fire at you until you are dead

**Comment by SM-BJS** [comment]
I will try to replicate this issue so I can try to figure it out but this might just be an Arma skill issue, will look into it though.

**Comment by SM-BJS** [comment]
After testing by Kiwi, this seems to only appear when in a Zeus slot. Since we have the bus system now anyway I will be removing the Vanilla respawn system and adding my system again in the next update.

**Comment by SM-BJS** [comment]
Fixed in Update 9.2.1
